"""initial database schema

Revision ID: 50eb0970aaf2
Revises: 
Create Date: 2026-08-30 23:40:46.333720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '50eb0970aaf2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OFFICER', 'SUPERVISOR', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('badge_id', sa.String(length=50), nullable=True),
    sa.Column('checkpoint', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('verification_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.String(length=50), nullable=False),
    sa.Column('officer_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('document_number', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('date_of_issue', sa.String(length=20), nullable=True),
    sa.Column('date_of_expiry', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('ocr_confidence', sa.Float(), nullable=True),
    sa.Column('mrz_detected', sa.Boolean(), nullable=True),
    sa.Column('mrz_checksum_valid', sa.Boolean(), nullable=True),
    sa.Column('consistency_name_match', sa.Boolean(), nullable=True),
    sa.Column('consistency_passport_match', sa.Boolean(), nullable=True),
    sa.Column('consistency_dob_match', sa.Boolean(), nullable=True),
    sa.Column('consistency_expiry_match', sa.Boolean(), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='verificationstatus'), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=True),
    sa.Column('verification_result', sa.String(length=50), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('fields_extracted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['officer_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_records_created_at'), 'verification_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_verification_records_document_number'), 'verification_records', ['document_number'], unique=False)
    op.create_index(op.f('ix_verification_records_officer_id'), 'verification_records', ['officer_id'], unique=False)
    op.create_index(op.f('ix_verification_records_risk_level'), 'verification_records', ['risk_level'], unique=False)
    op.create_index(op.f('ix_verification_records_verification_id'), 'verification_records', ['verification_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.Enum('LOGIN', 'LOGOUT', 'DOCUMENT_UPLOADED', 'DOCUMENT_VERIFIED', 'VERIFICATION_FAILED', 'RISK_SCORE_GENERATED', 'RECORD_VIEWED', 'RECORD_UPDATED', 'USER_CREATED', name='auditaction'), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['verification_id'], ['verification_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_verification_id'), 'audit_logs', ['verification_id'], unique=False)
    op.create_table('extracted_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('extracted_value', sa.String(length=500), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('validation_status', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['verification_id'], ['verification_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_fields_verification_id'), 'extracted_fields', ['verification_id'], unique=False)
    op.create_table('face_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('face_detected', sa.Boolean(), nullable=True),
    sa.Column('face_match', sa.Boolean(), nullable=True),
    sa.Column('similarity_score', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verification_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_verifications_verification_id'), 'face_verifications', ['verification_id'], unique=True)
    op.create_table('risk_assessments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risklevel'), nullable=False),
    sa.Column('risk_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('model_version', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verification_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_assessments_verification_id'), 'risk_assessments', ['verification_id'], unique=True)
    op.create_table('tampering_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('verification_id', sa.UUID(), nullable=False),
    sa.Column('tampering_detected', sa.Boolean(), nullable=True),
    sa.Column('tampering_score', sa.Float(), nullable=True),
    sa.Column('detected_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('analysis_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['verification_id'], ['verification_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tampering_analyses_verification_id'), 'tampering_analyses', ['verification_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tampering_analyses_verification_id'), table_name='tampering_analyses')
    op.drop_table('tampering_analyses')
    op.drop_index(op.f('ix_risk_assessments_verification_id'), table_name='risk_assessments')
    op.drop_table('risk_assessments')
    op.drop_index(op.f('ix_face_verifications_verification_id'), table_name='face_verifications')
    op.drop_table('face_verifications')
    op.drop_index(op.f('ix_extracted_fields_verification_id'), table_name='extracted_fields')
    op.drop_table('extracted_fields')
    op.drop_index(op.f('ix_audit_logs_verification_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_verification_records_verification_id'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_risk_level'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_officer_id'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_document_number'), table_name='verification_records')
    op.drop_index(op.f('ix_verification_records_created_at'), table_name='verification_records')
    op.drop_table('verification_records')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
